In [1]:
import pandas as pd
import altair as alt

In [4]:
data = pd.read_csv("../data/processed/val/data.csv")

In [5]:
data.head()

,Unnamed: 0,superflux,energy,rms,sound_preassure_level,welch,mean,kurtosis,skew,variation,onset,timestamps
0,0,0.00000,1.854257e+10,11829.067,-16.04423,23887228.0,-97.99023,3.78939,0.08069,-52.71864,True,0.05
1,1,0.67023,5.774538e+10,8706.333,-14.21874,41914464.0,-20.98438,0.31893,-0.17229,-303.80963,False,0.15
2,2,0.00030,4.272828e+10,7296.478,-14.86607,25699324.0,44.87402,-0.13543,0.44628,131.86375,True,0.25
3,3,0.00017,3.804206e+10,4892.303,-13.36547,26550460.0,386.51025,0.67891,0.02318,18.16960,True,0.35
4,4,0.44279,3.252422e+10,4125.005,-18.32991,17450054.0,248.43115,-0.19117,-0.62259,15.95452,False,0.45